// Shared builder for the portable Replace-image library bundle.
//
// The editor's Replace-image modal seeds its IndexedDB library from
// assets/image-library/. Fetching those files only works when the app is SERVED
// over http — opened from a zip via file:// the browser blocks fetch(). To make
// the library available in BOTH cases (and to make uploads permanent), we bake
// the listed images into a committed JS bundle (assets/image-library/library.js)
// that the editor loads via a plain <script> tag — no fetch required.
//
// Used by scripts/build-image-library.mjs (CLI) and the dev server's
// /save-image endpoint (persists uploads during authoring).

import { mkdir, readFile, writeFile, readdir } from 'node:fs/promises';
import path from 'node:path';

export const LIBRARY_DIRNAME = path.join('assets', 'image-library');
export const MANIFEST_NAME = 'manifest.json';
export const BUNDLE_NAME = 'library.js';

const MIME_BY_EXT = {
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.png': 'image/png',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.svg': 'image/svg+xml'
};

export const ALLOWED_MIME = new Set(Object.values(MIME_BY_EXT));

export function inferMime(filename) {
  return MIME_BY_EXT[path.extname(String(filename || '')).toLowerCase()] || '';
}

/** A filename safe to write inside the library folder (no path traversal). */
export function isSafeImageName(filename) {
  const f = String(filename || '');
  return /^[A-Za-z0-9._-]{1,80}$/.test(f) && !!inferMime(f);
}

async function readManifest(libDir) {
  try {
    const raw = await readFile(path.join(libDir, MANIFEST_NAME), 'utf8');
    const json = JSON.parse(raw);
    return json && typeof json === 'object' ? json : { images: [] };
  } catch {
    return { images: [] };
  }
}

async function writeManifest(libDir, manifest) {
  const out = {
    $comment: manifest.$comment ||
      "List the image filenames in assets/image-library/ so the editor's Replace-image modal pre-loads them. Run `npm run build:image-library` after editing to regenerate library.js.",
    images: Array.isArray(manifest.images) ? manifest.images : []
  };
  await writeFile(path.join(libDir, MANIFEST_NAME), JSON.stringify(out, null, 2) + '\n', 'utf8');
}

/**
 * Regenerate assets/image-library/library.js from the files listed in
 * manifest.json (skipping the manifest/bundle/readme and anything unreadable).
 * Returns { count, skipped }.
 */
export async function buildLibraryJs(libDir) {
  const manifest = await readManifest(libDir);
  const listed = Array.isArray(manifest.images) ? manifest.images : [];
  const images = [];
  const skipped = [];
  for (const name of listed) {
    const filename = String(name || '').trim();
    if (!filename || !isSafeImageName(filename)) { skipped.push(filename); continue; }
    try {
      const bytes = await readFile(path.join(libDir, filename));
      const mimeType = inferMime(filename);
      images.push({ filename, mimeType, dataUri: `data:${mimeType};base64,${bytes.toString('base64')}` });
    } catch {
      skipped.push(filename);
    }
  }
  const body = images.map((im) => '  ' + JSON.stringify(im)).join(',\n');
  const js =
    '/* eslint-disable */\n' +
    '/* AUTO-GENERATED by scripts/build-image-library.mjs — do not edit by hand.\n' +
    '   Portable Replace-image library: images embedded as data URIs so they load\n' +
    '   with or without a server (file:// and http). Regenerate: npm run build:image-library */\n' +
    'window.App = window.App || {};\n' +
    'window.App.ImageLibrary = { images: [\n' + body + (body ? '\n' : '') + '] };\n';
  await writeFile(path.join(libDir, BUNDLE_NAME), js, 'utf8');
  return { count: images.length, skipped };
}

/**
 * Persist an uploaded image into the project: write the file, ensure the
 * manifest lists it, then regenerate the bundle. `bytes` is a Buffer/Uint8Array.
 */
export async function addImage(libDir, filename, bytes) {
  if (!isSafeImageName(filename)) throw new Error('unsafe image filename');
  await mkdir(libDir, { recursive: true });
  await writeFile(path.join(libDir, filename), bytes);
  const manifest = await readManifest(libDir);
  const images = Array.isArray(manifest.images) ? manifest.images : [];
  if (!images.includes(filename)) images.push(filename);
  await writeManifest(libDir, { ...manifest, images });
  await buildLibraryJs(libDir);
  return { filename };
}

/** Best-effort: list image files actually present in the folder. */
export async function listImageFiles(libDir) {
  try {
    const entries = await readdir(libDir);
    return entries.filter(isSafeImageName);
  } catch {
    return [];
  }
}
