// AUTO-GENERATED by App.DB.exportArticleSeed() — do not hand-edit.
// Committed starter article set, seeded into every user's DB on first launch.
// Empty until populated: open the app, run App.DB.exportArticleSeed() in the console,
// save the result over this file, then commit. See article-seed/README.md.
window.App = window.App || {};
window.App.ArticleSeed = [];
