/**
 * Static design replicas (Beta).
 *
 * These 6 templates are full standalone HTML poster documents that live under
 * templates/reference/pipeline/. They are rendered VERBATIM — no template
 * tokens, no AI text-slot wiring, no dynamic article logic. Each registered
 * builder simply drops the original file's HTML into an isolated <iframe>
 * (srcdoc) so the poster's own <head> styles can't leak into the app shell and
 * the layout shows exactly as designed.
 *
 * Tiering: the catalog entries in newsletter_builder.js carry no
 * `status: 'testing'` flag, so the readiness loop classifies them as `beta`.
 * The lone testing template (gen_strong_passwords) is untouched by this file.
 *
 * Load order: AFTER js/newsletter/core_templates.js (needs the registration API
 * App.NewsletterBuilder.registerTemplate, which the core file installs).
 */
(function () {
  'use strict';

  const NB = window.App && window.App.NewsletterBuilder;
  if (!NB || typeof NB.registerTemplate !== 'function') return;

  // id -> source file (relative, zip-portable; served by `npm run serve`).
  // NB: gen_vishing and gen_social_engineering were upgraded to dynamic,
  // email-safe templates (buildGenVishing / buildGenSocialEngineering in
  // core_templates.js) — they are intentionally NOT here.
  const REPLICAS = {
    gen_phonescam:          'templates/reference/pipeline/phonescam_replica_light.html',
    gen_right_message:      'templates/reference/pipeline/right_message_replica.html',
    gen_spear_phishing:     'templates/reference/pipeline/spear_phishing_replica.html',
    gen_weakest_link:       'templates/reference/pipeline/weakest_link_replica_light.html',
    gen_wifi_safety:        'templates/reference/pipeline/wifi_safety_replica.html'
  };

  const cache = {}; // id -> raw HTML string

  // Seed the cache from the inlined bundle (js/newsletter/static_replicas_data.js,
  // generated by `npm run build:static-replicas`). This is what makes the posters
  // render with NO network — the only way they work from a zip opened via file://,
  // where fetch() of a local file is blocked. fetch() below stays as a dev/http
  // fallback for when the bundle isn't loaded.
  const INLINE = (window.App && window.App.StaticReplicaData) || {};
  Object.keys(REPLICAS).forEach((id) => {
    if (typeof INLINE[id] === 'string' && INLINE[id]) cache[id] = INLINE[id];
  });

  function prefetch(id) {
    const url = REPLICAS[id];
    if (!url || cache[id] != null) return; // already inlined → no fetch needed
    if (typeof fetch !== 'function') return;
    fetch(url)
      .then((r) => (r.ok ? r.text() : Promise.reject(r.status)))
      .then((t) => { cache[id] = t; })
      .catch(() => { /* leave uncached; builder shows a loading notice + retries */ });
  }

  // Warm any id NOT already inlined (dev/http only — inlined ids short-circuit).
  Object.keys(REPLICAS).forEach(prefetch);

  // srcdoc attribute escaping: escape & first (so existing entities like &rarr;
  // round-trip correctly), then the quote that delimits the attribute.
  function escSrcdoc(s) {
    return String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;');
  }

  // Real, scannable QR as a PNG data-URI (mirrors ui_controller.generateQrDataUriSync).
  // Gives the static posters the same working #nl-qr the ready templates render,
  // instead of the placeholder SVG shipped in the file. Returns '' if the QRCode
  // vendor lib isn't loaded yet (builder then leaves the placeholder untouched).
  function qrDataUri(text) {
    if (!text || typeof document === 'undefined' || typeof QRCode === 'undefined') return '';
    const holder = document.createElement('div');
    holder.style.cssText = 'position:absolute;left:-9999px;top:0;width:1px;height:1px;overflow:hidden';
    document.body.appendChild(holder);
    try {
      const qc = new QRCode(holder, {
        text, width: 144, height: 144,
        colorDark: '#000000', colorLight: '#ffffff',
        correctLevel: QRCode.CorrectLevel.H
      });
      void qc;
      const canvas = holder.querySelector('canvas');
      if (canvas) { try { return canvas.toDataURL('image/png'); } catch { /* tainted canvas */ } }
      const img = holder.querySelector('img');
      return (img && img.getAttribute('src')) || '';
    } catch {
      return '';
    } finally {
      holder.remove();
    }
  }

  // Replace the #nl-qr placeholder with a real QR <img>, preserving the FULL
  // standalone document (App.Utils.injectNlQrImageIntoHtml returns body.innerHTML
  // only, which would strip the replica's <head> styles — so we parse the whole doc).
  function injectQr(fullHtml, uri) {
    if (!uri || typeof DOMParser === 'undefined' || fullHtml.indexOf('nl-qr') === -1) return fullHtml;
    try {
      const doc = new DOMParser().parseFromString(fullHtml, 'text/html');
      const qr = doc.querySelector('#nl-qr');
      if (!qr) return fullHtml;
      const size = parseInt(qr.getAttribute('data-qr-size'), 10) || 144;
      qr.innerHTML = '';
      const img = doc.createElement('img');
      img.setAttribute('src', uri);
      img.setAttribute('alt', 'Scan for the security awareness portal');
      img.setAttribute('width', String(size));
      img.setAttribute('height', String(size));
      img.setAttribute('style', 'display:block;width:' + size + 'px;height:' + size + 'px;');
      qr.appendChild(img);
      return (doc.doctype ? '<!DOCTYPE html>' : '') + doc.documentElement.outerHTML;
    } catch {
      return fullHtml;
    }
  }

  // Wire the awareness-portal footer to Config so the static posters match the
  // ready templates (which read cfg.pname / cfg.portal): the portal NAME fills
  // #nl-portal-name and the "Visit Portal" link's href fills #nl-portal-link.
  // Both hooks are seeded in the replica HTML; a replica missing them (or a Config
  // with no value) is left exactly as authored — same defensive contract as injectQr.
  function injectPortalDetails(fullHtml, cfg) {
    if (typeof DOMParser === 'undefined') return fullHtml;
    if (fullHtml.indexOf('nl-portal-name') === -1 && fullHtml.indexOf('nl-portal-link') === -1) return fullHtml;
    try {
      const doc = new DOMParser().parseFromString(fullHtml, 'text/html');
      const name = cfg && String((cfg.pname || cfg.title || '')).trim();
      const nameEl = doc.querySelector('#nl-portal-name');
      if (nameEl && name) nameEl.textContent = name;
      const href = resolvePortal(cfg);
      const linkEl = doc.querySelector('#nl-portal-link');
      if (linkEl && href) linkEl.setAttribute('href', href);
      return (doc.doctype ? '<!DOCTYPE html>' : '') + doc.documentElement.outerHTML;
    } catch {
      return fullHtml;
    }
  }

  // The QR encodes the portal URL the user enters in Config (cfg.portal) — never
  // a hardcoded link. If Config has no portal, returns '' so no QR is injected
  // and the file's placeholder is left as-is.
  function resolvePortal(cfg) {
    const raw = cfg && String(cfg.portal || cfg.portalUrl || '').trim();
    if (!raw) return '';
    const u = window.App && window.App.Utils;
    return u && typeof u.normalizeWebUrl === 'function' ? u.normalizeWebUrl(raw) : raw;
  }

  // Returns a <td>-valid fragment (build() wraps it in <table><tr><td>…).
  // build() calls the builder as fn(cfg, arts, …), so cfg.portal drives the QR.
  function makeBuilder(id) {
    return function staticReplicaBuilder(cfg) {
      let raw = cache[id];
      if (raw == null) {
        prefetch(id); // kick a (re)fetch; a rebuild in a moment will render it
        return '<div style="padding:48px 24px;text-align:center;font-family:Arial,Helvetica,sans-serif;font-size:14px;color:#555;">'
          + 'Loading static template… click Generate again in a moment.</div>';
      }
      // Bake a live, scannable QR (encoding the configured portal URL) into
      // #nl-qr — same functionality as the ready templates' QR block.
      const uri = qrDataUri(resolvePortal(cfg));
      if (uri) raw = injectQr(raw, uri);
      // Fill the portal name + "Visit Portal" link from Config (no-op for
      // replicas without the #nl-portal-* hooks, e.g. the other five posters).
      raw = injectPortalDetails(raw, cfg);
      return '<iframe title="' + id + '" scrolling="no" '
        + 'style="width:100%;border:0;display:block;background:#FFFFFF;" '
        + 'srcdoc="' + escSrcdoc(raw) + '" '
        + 'onload="try{this.style.height=(this.contentWindow.document.documentElement.scrollHeight+20)+\'px\';}catch(e){}">'
        + '</iframe>';
    };
  }

  Object.keys(REPLICAS).forEach((id) => NB.registerTemplate(id, makeBuilder(id)));
})();
