/**
 * Static design replicas (Beta).
 *
 * These 6 templates are full standalone HTML poster documents that live under
 * templates/reference/pipeline/. They are rendered VERBATIM — no template
 * tokens, no AI text-slot wiring, no dynamic article logic. Each registered
 * builder simply drops the original file's HTML into an isolated <iframe>
 * (srcdoc) so the poster's own <head> styles can't leak into the app shell and
 * the layout shows exactly as designed.
 *
 * Tiering: the catalog entries in newsletter_builder.js carry no
 * `status: 'testing'` flag, so the readiness loop classifies them as `beta`.
 * The lone testing template (gen_strong_passwords) is untouched by this file.
 *
 * Load order: AFTER js/newsletter/core_templates.js (needs the registration API
 * App.NewsletterBuilder.registerTemplate, which the core file installs).
 */
(function () {
  'use strict';

  const NB = window.App && window.App.NewsletterBuilder;
  if (!NB || typeof NB.registerTemplate !== 'function') return;

  // id -> source file (relative, zip-portable; served by `npm run serve`).
  // NB: gen_vishing and gen_social_engineering were upgraded to dynamic,
  // email-safe templates (buildGenVishing / buildGenSocialEngineering in
  // core_templates.js) — they are intentionally NOT here.
  const REPLICAS = {
    gen_phonescam:          'templates/reference/pipeline/phonescam_replica_light.html',
    gen_right_message:      'templates/reference/pipeline/right_message_replica.html',
    gen_spear_phishing:     'templates/reference/pipeline/spear_phishing_replica.html',
    gen_weakest_link:       'templates/reference/pipeline/weakest_link_replica_light.html',
    gen_wifi_safety:        'templates/reference/pipeline/wifi_safety_replica.html',
    gen_horizontal_brief:   'templates/reference/pipeline/horizontal_brief_replica.html',
    gen_security_digest:    'templates/reference/pipeline/weekly_security_report_replica.html'
  };

  const cache = {}; // id -> raw HTML string

  // Seed the cache from the inlined bundle (js/newsletter/static_replicas_data.js,
  // generated by `npm run build:static-replicas`). This is what makes the posters
  // render with NO network — the only way they work from a zip opened via file://,
  // where fetch() of a local file is blocked. fetch() below stays as a dev/http
  // fallback for when the bundle isn't loaded.
  const INLINE = (window.App && window.App.StaticReplicaData) || {};
  Object.keys(REPLICAS).forEach((id) => {
    if (typeof INLINE[id] === 'string' && INLINE[id]) cache[id] = INLINE[id];
  });

  function prefetch(id) {
    const url = REPLICAS[id];
    if (!url || cache[id] != null) return; // already inlined → no fetch needed
    if (typeof fetch !== 'function') return;
    fetch(url)
      .then((r) => (r.ok ? r.text() : Promise.reject(r.status)))
      .then((t) => { cache[id] = t; })
      .catch(() => { /* leave uncached; builder shows a loading notice + retries */ });
  }

  // Warm any id NOT already inlined (dev/http only — inlined ids short-circuit).
  Object.keys(REPLICAS).forEach(prefetch);

  // srcdoc attribute escaping: escape & first (so existing entities like &rarr;
  // round-trip correctly), then the quote that delimits the attribute.
  function escSrcdoc(s) {
    return String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;');
  }

  // These three posters are AI-wired (article-driven copy injected into their
  // #nl-* hooks) AND must be translatable + editable. The remaining four are
  // verbatim static designs that stay in an isolated iframe. The replicas are
  // pure inline-styled tables (no <head>/<style>/class dependency), so rendering
  // the <body> contents DIRECTLY in the document is visually identical to the
  // iframe — but the text now lives in the main DOM, so the per-fragment
  // translator and the editor reach it, and it survives .eml export (iframes do
  // not). For the other four, the iframe stays (no AI text, design isolation).
  const INLINE_IDS = new Set(['gen_wifi_safety', 'gen_horizontal_brief', 'gen_security_digest']);

  // Return a replica's <body> inner HTML (a self-contained, centered email-safe
  // table) for inline rendering. In Node (no DOMParser, unit tests) the HTML is
  // returned unchanged — the inline path is a browser-runtime concern.
  function inlineBody(html) {
    if (typeof DOMParser === 'undefined') return html;
    try {
      const doc = new DOMParser().parseFromString(html, 'text/html');
      if (doc && doc.body) {
        // Rendered inline (not iframed), these anchors live in the main app
        // document — without the iframe's <base target="_blank"> a click would
        // navigate the whole app away. Force every link to open in a new tab.
        const links = doc.body.querySelectorAll('a[href]');
        for (let i = 0; i < links.length; i++) {
          links[i].setAttribute('target', '_blank');
          links[i].setAttribute('rel', 'noopener noreferrer');
        }
        return doc.body.innerHTML;
      }
    } catch (e) { /* fall through */ }
    return html;
  }

  // Real, scannable QR as a PNG data-URI (mirrors ui_controller.generateQrDataUriSync).
  // Gives the static posters the same working #nl-qr the ready templates render,
  // instead of the placeholder SVG shipped in the file. Returns '' if the QRCode
  // vendor lib isn't loaded yet (builder then leaves the placeholder untouched).
  function qrDataUri(text) {
    if (!text || typeof document === 'undefined' || typeof QRCode === 'undefined') return '';
    const holder = document.createElement('div');
    holder.style.cssText = 'position:absolute;left:-9999px;top:0;width:1px;height:1px;overflow:hidden';
    document.body.appendChild(holder);
    try {
      const qc = new QRCode(holder, {
        text, width: 144, height: 144,
        colorDark: '#000000', colorLight: '#ffffff',
        correctLevel: QRCode.CorrectLevel.H
      });
      void qc;
      const canvas = holder.querySelector('canvas');
      if (canvas) { try { return canvas.toDataURL('image/png'); } catch { /* tainted canvas */ } }
      const img = holder.querySelector('img');
      return (img && img.getAttribute('src')) || '';
    } catch {
      return '';
    } finally {
      holder.remove();
    }
  }

  // Replace the #nl-qr placeholder with a real QR <img>, preserving the FULL
  // standalone document (App.Utils.injectNlQrImageIntoHtml returns body.innerHTML
  // only, which would strip the replica's <head> styles — so we parse the whole doc).
  function injectQr(fullHtml, uri) {
    if (!uri || typeof DOMParser === 'undefined' || fullHtml.indexOf('nl-qr') === -1) return fullHtml;
    try {
      const doc = new DOMParser().parseFromString(fullHtml, 'text/html');
      const qr = doc.querySelector('#nl-qr');
      if (!qr) return fullHtml;
      const size = parseInt(qr.getAttribute('data-qr-size'), 10) || 144;
      qr.innerHTML = '';
      const img = doc.createElement('img');
      img.setAttribute('src', uri);
      img.setAttribute('alt', 'Scan for the security awareness portal');
      img.setAttribute('width', String(size));
      img.setAttribute('height', String(size));
      img.setAttribute('style', 'display:block;width:' + size + 'px;height:' + size + 'px;');
      qr.appendChild(img);
      return (doc.doctype ? '<!DOCTYPE html>' : '') + doc.documentElement.outerHTML;
    } catch {
      return fullHtml;
    }
  }

  // Wire the awareness-portal footer to Config so the static posters match the
  // ready templates (which read cfg.pname / cfg.portal): the portal NAME fills
  // #nl-portal-name and the "Visit Portal" link's href fills #nl-portal-link.
  // Both hooks are seeded in the replica HTML; a replica missing them (or a Config
  // with no value) is left exactly as authored — same defensive contract as injectQr.
  function injectPortalDetails(fullHtml, cfg) {
    if (typeof DOMParser === 'undefined') return fullHtml;
    if (fullHtml.indexOf('nl-portal-name') === -1 && fullHtml.indexOf('nl-portal-link') === -1) return fullHtml;
    try {
      const doc = new DOMParser().parseFromString(fullHtml, 'text/html');
      const name = cfg && String((cfg.pname || cfg.title || '')).trim();
      const nameEl = doc.querySelector('#nl-portal-name');
      if (nameEl && name) nameEl.textContent = name;
      const href = resolvePortal(cfg);
      const linkEl = doc.querySelector('#nl-portal-link');
      if (linkEl && href) linkEl.setAttribute('href', href);
      return (doc.doctype ? '<!DOCTYPE html>' : '') + doc.documentElement.outerHTML;
    } catch {
      return fullHtml;
    }
  }

  // Fill the Wi-Fi Safety poster's AI text slots into the id hooks seeded in
  // wifi_safety_replica.html (#nl-wifi-intro, #nl-wifi-tip1..5). The slots arrive
  // on cfg from fillNewsletterTextSlots('gen_wifi_safety', …): present only when an
  // AI key produced article-driven content. Same defensive contract as
  // injectPortalDetails — a replica without the hooks (the other four posters) or a
  // cfg without the slots (no AI) is left EXACTLY as authored, so the design and the
  // default Wi-Fi copy stay byte-identical when AI is off. textContent (not
  // innerHTML) keeps the injection safe; it replaces the authored <strong>+text.
  function injectWifiText(fullHtml, cfg) {
    if (typeof DOMParser === 'undefined') return fullHtml;
    if (fullHtml.indexOf('nl-wifi-') === -1) return fullHtml;
    const heading = cfg && typeof cfg.nlWifiHeading === 'string' ? cfg.nlWifiHeading.trim() : '';
    const intro = cfg && typeof cfg.nlWifiIntro === 'string' ? cfg.nlWifiIntro.trim() : '';
    const tips = cfg && Array.isArray(cfg.nlWifiTips) ? cfg.nlWifiTips : [];
    // White-side heading above the tips: the poster flip-form theme. Shown only when a
    // theme was chosen; otherwise the whole block is removed so the poster is unchanged.
    const tipsHeading = cfg && typeof cfg.nlWifiTipsHeading === 'string' ? cfg.nlWifiTipsHeading.trim() : '';
    const hasTipsHeadingBlock = fullHtml.indexOf('nl-wifi-tips-heading-block') !== -1;
    // Proceed if there is any AI copy, a theme to show, OR a theme block to strip.
    if (!heading && !intro && !tipsHeading && !hasTipsHeadingBlock && !tips.some((t) => String(t || '').trim())) return fullHtml;
    try {
      const doc = new DOMParser().parseFromString(fullHtml, 'text/html');
      const tipsHeadBlock = doc.querySelector('#nl-wifi-tips-heading-block');
      if (tipsHeadBlock) {
        if (tipsHeading) {
          const el = doc.querySelector('#nl-wifi-tips-heading'); if (el) el.textContent = tipsHeading;
        } else if (tipsHeadBlock.parentNode) {
          tipsHeadBlock.parentNode.removeChild(tipsHeadBlock);  // no theme → no white-side heading
        }
      }
      if (heading) { const el = doc.querySelector('#nl-wifi-heading'); if (el) el.textContent = heading; }
      if (intro) { const el = doc.querySelector('#nl-wifi-intro'); if (el) el.textContent = intro; }
      for (let i = 0; i < 5; i++) {
        const t = String(tips[i] || '').trim();
        if (!t) continue;
        const el = doc.querySelector('#nl-wifi-tip' + (i + 1));
        if (el) el.textContent = t;
      }
      return (doc.doctype ? '<!DOCTYPE html>' : '') + doc.documentElement.outerHTML;
    } catch {
      return fullHtml;
    }
  }

  // Attribute the source article on the Wi-Fi poster: fill #nl-wifi-source-name and
  // the #nl-wifi-source-link href from the selected article (arts[0]). No article →
  // the whole #nl-wifi-source-row is removed; a source but no usable web URL → just
  // the link + separator are dropped. Same defensive contract as the other injectors:
  // no hooks (the other replicas) → returned unchanged. textContent + an http(s)-only
  // href keep it safe from injection.
  function injectWifiSource(fullHtml, arts) {
    if (typeof DOMParser === 'undefined') return fullHtml;
    if (fullHtml.indexOf('nl-wifi-source-row') === -1) return fullHtml;
    const a = (Array.isArray(arts) ? arts : [])[0] || {};
    const source = String(a.source || '').trim();
    const rawUrl = String(a.url || a.link || '').trim();
    const url = /^https?:\/\//i.test(rawUrl) ? rawUrl : '';
    try {
      const doc = new DOMParser().parseFromString(fullHtml, 'text/html');
      const row = doc.querySelector('#nl-wifi-source-row');
      if (!row) return fullHtml;
      if (!source && !url) {
        if (row.parentNode) row.parentNode.removeChild(row);
        return (doc.doctype ? '<!DOCTYPE html>' : '') + doc.documentElement.outerHTML;
      }
      const nameEl = doc.querySelector('#nl-wifi-source-name');
      if (nameEl) nameEl.textContent = source ? ('Source: ' + source) : 'Source';
      const linkEl = doc.querySelector('#nl-wifi-source-link');
      const sepEl = doc.querySelector('#nl-wifi-source-sep');
      if (url) {
        if (linkEl) linkEl.setAttribute('href', url);
      } else {
        if (linkEl && linkEl.parentNode) linkEl.parentNode.removeChild(linkEl);
        if (sepEl && sepEl.parentNode) sepEl.parentNode.removeChild(sepEl);
      }
      return (doc.doctype ? '<!DOCTYPE html>' : '') + doc.documentElement.outerHTML;
    } catch {
      return fullHtml;
    }
  }

  // Fill the Horizontal Brief poster's AI text slots into the id hooks seeded in
  // horizontal_brief_replica.html (#nl-hb-heading, #nl-hb-intro, #nl-hb-tip1..4).
  // Same defensive contract as injectWifiText: a replica without the hooks, or a cfg
  // without the slots (no AI), is left EXACTLY as authored, so the design and the
  // authored phishing copy stay byte-identical when AI is off.
  function injectHbText(fullHtml, cfg) {
    if (typeof DOMParser === 'undefined') return fullHtml;
    if (fullHtml.indexOf('nl-hb-') === -1) return fullHtml;
    const heading = cfg && typeof cfg.nlHbHeading === 'string' ? cfg.nlHbHeading.trim() : '';
    const intro = cfg && typeof cfg.nlHbIntro === 'string' ? cfg.nlHbIntro.trim() : '';
    const tips = cfg && Array.isArray(cfg.nlHbTips) ? cfg.nlHbTips : [];
    if (!heading && !intro && !tips.some((t) => String(t || '').trim())) return fullHtml;
    try {
      const doc = new DOMParser().parseFromString(fullHtml, 'text/html');
      if (heading) {
        const el = doc.querySelector('#nl-hb-heading');
        if (el) {
          el.textContent = heading;
          // The authored slogan is short (big display type); real article headlines run
          // longer — scale the heading down by length so it stays inside the black band.
          const n = heading.length;
          const fs = n <= 22 ? 38 : n <= 34 ? 32 : n <= 50 ? 26 : n <= 72 ? 22 : 19;
          el.style.fontSize = fs + 'px';
        }
      }
      if (intro) { const el = doc.querySelector('#nl-hb-intro'); if (el) el.textContent = intro; }
      for (let i = 0; i < 4; i++) {
        const t = String(tips[i] || '').trim();
        if (!t) continue;
        const el = doc.querySelector('#nl-hb-tip' + (i + 1));
        if (el) el.textContent = t;
      }
      return (doc.doctype ? '<!DOCTYPE html>' : '') + doc.documentElement.outerHTML;
    } catch {
      return fullHtml;
    }
  }

  // Attribute the source article on the Horizontal Brief poster, mirroring
  // injectWifiSource: fill #nl-hb-source-name + #nl-hb-source-link from arts[0], remove
  // the whole #nl-hb-source-row when there is no article, drop just the link + separator
  // when there is a source but no usable web URL. textContent + an http(s)-only href.
  function injectHbSource(fullHtml, arts) {
    if (typeof DOMParser === 'undefined') return fullHtml;
    if (fullHtml.indexOf('nl-hb-source-row') === -1) return fullHtml;
    const a = (Array.isArray(arts) ? arts : [])[0] || {};
    const source = String(a.source || '').trim();
    const rawUrl = String(a.url || a.link || '').trim();
    const url = /^https?:\/\//i.test(rawUrl) ? rawUrl : '';
    try {
      const doc = new DOMParser().parseFromString(fullHtml, 'text/html');
      const row = doc.querySelector('#nl-hb-source-row');
      if (!row) return fullHtml;
      if (!source && !url) {
        if (row.parentNode) row.parentNode.removeChild(row);
        return (doc.doctype ? '<!DOCTYPE html>' : '') + doc.documentElement.outerHTML;
      }
      const nameEl = doc.querySelector('#nl-hb-source-name');
      if (nameEl) nameEl.textContent = source ? ('Source: ' + source) : 'Source';
      const linkEl = doc.querySelector('#nl-hb-source-link');
      const sepEl = doc.querySelector('#nl-hb-source-sep');
      if (url) {
        if (linkEl) linkEl.setAttribute('href', url);
      } else {
        if (linkEl && linkEl.parentNode) linkEl.parentNode.removeChild(linkEl);
        if (sepEl && sepEl.parentNode) sepEl.parentNode.removeChild(sepEl);
      }
      return (doc.doctype ? '<!DOCTYPE html>' : '') + doc.documentElement.outerHTML;
    } catch {
      return fullHtml;
    }
  }

  // Inject AI copy into the gen_security_digest weekly-digest replica
  // (#nl-sd-heading, #nl-sd-intro, #nl-sd-point1..4). Same defensive contract as
  // injectHbText: a replica without the hooks, or a cfg without the slots (AI off),
  // is returned EXACTLY as authored so the design + authored copy stay byte-identical.
  function injectSdText(fullHtml, cfg) {
    if (typeof DOMParser === 'undefined') return fullHtml;
    if (fullHtml.indexOf('nl-sd-') === -1) return fullHtml;
    const heading = cfg && typeof cfg.nlSdHeading === 'string' ? cfg.nlSdHeading.trim() : '';
    const intro = cfg && typeof cfg.nlSdIntro === 'string' ? cfg.nlSdIntro.trim() : '';
    const points = cfg && Array.isArray(cfg.nlSdPoints) ? cfg.nlSdPoints : [];
    if (!heading && !intro && !points.some((p) => String(p || '').trim())) return fullHtml;
    try {
      const doc = new DOMParser().parseFromString(fullHtml, 'text/html');
      if (heading) { const el = doc.querySelector('#nl-sd-heading'); if (el) el.textContent = heading; }
      if (intro) { const el = doc.querySelector('#nl-sd-intro'); if (el) el.textContent = intro; }
      for (let i = 0; i < 4; i++) {
        const p = String(points[i] || '').trim();
        if (!p) continue;
        const el = doc.querySelector('#nl-sd-point' + (i + 1));
        if (el) el.textContent = p;
      }
      return (doc.doctype ? '<!DOCTYPE html>' : '') + doc.documentElement.outerHTML;
    } catch {
      return fullHtml;
    }
  }

  // The QR encodes the portal URL the user enters in Config (cfg.portal) — never
  // a hardcoded link. If Config has no portal, returns '' so no QR is injected
  // and the file's placeholder is left as-is.
  function resolvePortal(cfg) {
    const raw = cfg && String(cfg.portal || cfg.portalUrl || '').trim();
    if (!raw) return '';
    const u = window.App && window.App.Utils;
    return u && typeof u.normalizeWebUrl === 'function' ? u.normalizeWebUrl(raw) : raw;
  }

  // Returns a <td>-valid fragment (build() wraps it in <table><tr><td>…).
  // build() calls the builder as fn(cfg, arts, …), so cfg.portal drives the QR.
  function makeBuilder(id) {
    return function staticReplicaBuilder(cfg, arts) {
      let raw = cache[id];
      if (raw == null) {
        prefetch(id); // kick a (re)fetch; a rebuild in a moment will render it
        return '<div style="padding:48px 24px;text-align:center;font-family:Arial,Helvetica,sans-serif;font-size:14px;color:#555;">'
          + 'Loading static template… click Generate again in a moment.</div>';
      }
      // Bake a live, scannable QR (encoding the configured portal URL) into
      // #nl-qr — same functionality as the ready templates' QR block.
      const uri = qrDataUri(resolvePortal(cfg));
      if (uri) raw = injectQr(raw, uri);
      // Fill the portal name + "Visit Portal" link from Config (no-op for
      // replicas without the #nl-portal-* hooks, e.g. the other five posters).
      raw = injectPortalDetails(raw, cfg);
      // Wire the footer "Visit Portal" button to the configured portal — the
      // replicas ship it as a dead href="#" (the URL is per-user). Falls back to
      // mailto:soc when no portal is set, matching the ready templates' foot().
      const U = window.App && window.App.Utils;
      if (U && typeof U.wireVisitPortalCta === 'function') {
        const portalCta = resolvePortal(cfg) || (cfg && cfg.soc ? 'mailto:' + String(cfg.soc).trim() : '');
        if (portalCta) raw = U.wireVisitPortalCta(raw, portalCta);
      }
      // Inject AI-generated Wi-Fi copy into the gen_wifi_safety hooks (no-op for
      // the other replicas, and when no AI slots are present).
      raw = injectWifiText(raw, cfg);
      // Attribute the source article (name + link) below the points, from the
      // selected article — removed when there is no article (e.g. the preview).
      raw = injectWifiSource(raw, arts);
      // Same wiring for the Horizontal Brief poster (no-op for every other replica
      // and when no AI slots / no article are present).
      raw = injectHbText(raw, cfg);
      raw = injectHbSource(raw, arts);
      // gen_security_digest: AI heading + intro + 4 points (no-op for every other
      // replica and when no AI slots are present).
      raw = injectSdText(raw, cfg);
      // The three AI-wired posters render INLINE (translatable / editable / email-
      // exportable); the four verbatim designs stay in an isolated iframe.
      if (INLINE_IDS.has(id)) return inlineBody(raw);
      return '<iframe title="' + id + '" scrolling="no" '
        + 'style="width:100%;border:0;display:block;background:#FFFFFF;" '
        + 'srcdoc="' + escSrcdoc(raw) + '" '
        + 'onload="try{this.style.height=(this.contentWindow.document.documentElement.scrollHeight+20)+\'px\';}catch(e){}">'
        + '</iframe>';
    };
  }

  Object.keys(REPLICAS).forEach((id) => NB.registerTemplate(id, makeBuilder(id)));
})();
