/* ═══════════════════════════════════════════════════════════
   advisory_send_script.js — App.AdvisorySendScript

   Generates a SELF-CONTAINED Python sender for the current advisory workspace,
   replicating the standalone nessus_advisory.py / cve_alert.py "zip" method:
   no relay, no server — the user runs `python send_advisories.py`, enters the
   sender + recipients, and it sends ONE EMAIL PER ADVISORY straight over SMTP.

   render(advisories, defaults) → Python source string.
     advisories: [{ subject, html, attachments:[{contentId,base64,contentType,filename}] }]
     defaults:   { senderName, senderEmail, host, port, username, recipients }

   The advisories + suggested defaults are embedded as base64(JSON) so the HTML
   (with its inline cid: images) never has to be escaped into Python literals.
   ═══════════════════════════════════════════════════════════ */
window.App = window.App || {};

App.AdvisorySendScript = (() => {
  'use strict';

  // ── Dependency-free UTF-8 → base64 ──
  // Implemented by hand (no btoa/Buffer/TextEncoder) so it behaves identically
  // in the browser and in the Node vm sandbox the unit tests run the module in.
  function utf8Bytes(str) {
    const out = [];
    for (let i = 0; i < str.length; i++) {
      let c = str.charCodeAt(i);
      if (c < 0x80) {
        out.push(c);
      } else if (c < 0x800) {
        out.push(0xc0 | (c >> 6), 0x80 | (c & 0x3f));
      } else if (c >= 0xd800 && c <= 0xdbff && i + 1 < str.length) {
        const hi = c;
        const lo = str.charCodeAt(++i);
        const cp = 0x10000 + ((hi - 0xd800) << 10) + (lo - 0xdc00);
        out.push(
          0xf0 | (cp >> 18),
          0x80 | ((cp >> 12) & 0x3f),
          0x80 | ((cp >> 6) & 0x3f),
          0x80 | (cp & 0x3f)
        );
      } else {
        out.push(0xe0 | (c >> 12), 0x80 | ((c >> 6) & 0x3f), 0x80 | (c & 0x3f));
      }
    }
    return out;
  }

  const B64_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

  function bytesToBase64(bytes) {
    let out = '';
    for (let i = 0; i < bytes.length; i += 3) {
      const b0 = bytes[i];
      const has1 = i + 1 < bytes.length;
      const has2 = i + 2 < bytes.length;
      const b1 = has1 ? bytes[i + 1] : 0;
      const b2 = has2 ? bytes[i + 2] : 0;
      out += B64_ALPHABET[b0 >> 2];
      out += B64_ALPHABET[((b0 & 0x03) << 4) | (b1 >> 4)];
      out += has1 ? B64_ALPHABET[((b1 & 0x0f) << 2) | (b2 >> 6)] : '=';
      out += has2 ? B64_ALPHABET[b2 & 0x3f] : '=';
    }
    return out;
  }

  function utf8ToBase64(str) {
    return bytesToBase64(utf8Bytes(String(str)));
  }

  // ── Python template ──
  // String.raw so backslashes in the embedded Python (regex \1, \s, \n …) are
  // emitted verbatim instead of being eaten by JS escape processing. The single
  // placeholder __PAYLOAD_B64__ is replaced with the base64(JSON) payload.
  // Console output is kept ASCII-only (encode("ascii","replace")) so it never
  // raises UnicodeEncodeError on a legacy Windows console code page.
  const PY_TEMPLATE = String.raw`#!/usr/bin/env python3
"""
send_advisories.py  --  generated by the Awareness app.

Sends the advisories you generated as ONE EMAIL PER ADVISORY, the same way the
standalone nessus_advisory.py tool does: one server.sendmail() per advisory over
Gmail SMTP. No relay and no server.

CREDENTIALS -- the SAME environment variables as nessus_advisory.py. In the same
PowerShell window, set them, then run the script:

    $env:GMAIL_SENDER   = "you@gmail.com"
    $env:GMAIL_PASSWORD = "xxxx xxxx xxxx xxxx"     # Gmail App Password
    $env:EMAIL_TO       = "recipient@example.com"   # comma-separate for several

    python send_advisories.py

Anything you do NOT set in the environment is simply asked for at the prompt, so
you can just enter the sender + recipients. Credentials are used for this run
only and are never written to disk.

Gmail needs a 16-character App Password (not your normal password), with 2-Step
Verification enabled:  myaccount.google.com -> Security -> App passwords
(Sending through an internal relay that needs no login? Leave GMAIL_PASSWORD
unset, or blank at the prompt.)
"""

import base64
import getpass
import json
import os
import re
import smtplib
import sys
from email.header import Header
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import formataddr, formatdate, make_msgid

# Embedded advisories + suggested defaults (base64 of a JSON document).
_PAYLOAD_B64 = "__PAYLOAD_B64__"

PAYLOAD    = json.loads(base64.b64decode(_PAYLOAD_B64).decode("utf-8"))
DEFAULTS   = PAYLOAD.get("defaults", {})
ADVISORIES = PAYLOAD.get("advisories", [])


def _ascii(text):
    """Console-safe rendering -- avoids UnicodeEncodeError on legacy code pages."""
    return str(text).encode("ascii", "replace").decode("ascii")


def ask(label, default=""):
    shown = " [" + str(default) + "]" if default else ""
    value = input("  " + label + shown + ": ").strip()
    return value or default


def resolve_credentials():
    """Credentials come from the same environment variables nessus_advisory.py
    uses -- GMAIL_SENDER / GMAIL_PASSWORD / EMAIL_TO. Anything not set in the
    environment is asked for at the prompt (so a fully-env run is non-interactive,
    exactly like nessus_advisory.py; otherwise you just enter sender + recipients).
    SMTP host/port default to Gmail and can be overridden with SMTP_HOST/SMTP_PORT."""
    print()
    print("=" * 64)
    print("  SEND ADVISORIES  --  one email per advisory")
    print("  " + str(len(ADVISORIES)) + " advisory(ies) ready to send.")
    print("  Credentials are used for this run ONLY -- never saved to disk.")
    print("=" * 64)
    print()

    host = os.environ.get("SMTP_HOST") or DEFAULTS.get("host") or "smtp.gmail.com"
    port_raw = os.environ.get("SMTP_PORT") or str(DEFAULTS.get("port") or 587)
    sender_name = os.environ.get("GMAIL_SENDER_NAME") or DEFAULTS.get("senderName") or ""

    sender = os.environ.get("GMAIL_SENDER") or DEFAULTS.get("senderEmail") or DEFAULTS.get("username") or ""
    if not sender:
        sender = ask("Sender email address (GMAIL_SENDER)", "")

    recipients_raw = os.environ.get("EMAIL_TO") or DEFAULTS.get("recipients") or ""
    if not recipients_raw:
        recipients_raw = ask("Recipient(s), comma-separated (EMAIL_TO)", "")
    recipients = [r.strip() for r in recipients_raw.split(",") if r.strip()]

    # GMAIL_PASSWORD may be intentionally empty for an internal/no-auth relay, so
    # only fall back to the prompt when the variable is entirely unset.
    password = os.environ.get("GMAIL_PASSWORD")
    if password is None:
        password = getpass.getpass("  App password (GMAIL_PASSWORD; blank = internal/no-auth relay): ")

    missing = []
    if not host:
        missing.append("SMTP host")
    if not sender:
        missing.append("Sender email (GMAIL_SENDER)")
    if not recipients:
        missing.append("Recipient(s) (EMAIL_TO)")
    if missing:
        sys.exit("\n[ERROR] Missing required value(s): " + ", ".join(missing) + "\n")

    try:
        port_num = int(port_raw)
    except ValueError:
        port_num = 587

    return host, port_num, sender_name, sender, password, recipients


def plain_text_from_html(html):
    text = re.sub(r"(?is)<(script|style)[^>]*>.*?</\1>", " ", html)
    text = re.sub(r"(?i)<br\s*/?>", "\n", text)
    text = re.sub(r"(?i)</(p|div|tr|h[1-6])>", "\n", text)
    text = re.sub(r"<[^>]+>", " ", text)
    text = text.replace("&nbsp;", " ").replace("&amp;", "&")
    text = text.replace("&lt;", "<").replace("&gt;", ">").replace("&#39;", "'")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n[ \t]+", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip() or "This message requires an HTML-capable email client."


def build_message(advisory, sender_name, sender, recipients):
    """multipart/mixed -> related -> alternative(plain + html) -> inline cid images,
    mirroring cve_alert.py so images render inline in Outlook + Gmail."""
    subject = advisory.get("subject") or "Security Advisory"
    html = advisory.get("html") or ""
    attachments = advisory.get("attachments") or []

    outer = MIMEMultipart("mixed")
    outer["Subject"] = Header(subject, "utf-8")
    outer["From"] = formataddr((sender_name, sender)) if sender_name else sender
    outer["To"] = ", ".join(recipients)
    outer["Date"] = formatdate(localtime=True)
    domain = sender.split("@")[-1] if "@" in sender else "awareness.local"
    outer["Message-ID"] = make_msgid(domain=domain)
    outer["X-Mailer"] = "Awareness-Advisory-Sender/1.0"

    related = MIMEMultipart("related")
    alternative = MIMEMultipart("alternative")
    alternative.attach(MIMEText(plain_text_from_html(html), "plain", "utf-8"))
    alternative.attach(MIMEText(html, "html", "utf-8"))
    related.attach(alternative)

    for att in attachments:
        cid = str(att.get("contentId") or "").strip()
        data = str(att.get("base64") or "").strip()
        if not cid or not data:
            continue
        try:
            raw = base64.b64decode(data)
        except Exception:
            continue
        ctype = str(att.get("contentType") or "image/png")
        subtype = ctype.split("/", 1)[1] if "/" in ctype else "png"
        image = MIMEImage(raw, _subtype=subtype)
        image.add_header("Content-ID", "<" + cid + ">")
        image.add_header("Content-Disposition", "inline",
                         filename=str(att.get("filename") or (cid + "." + subtype)))
        related.attach(image)

    outer.attach(related)
    return outer


def connect(host, port):
    if port == 465:
        server = smtplib.SMTP_SSL(host, port, timeout=30)
        server.ehlo()
    else:
        server = smtplib.SMTP(host, port, timeout=30)
        server.ehlo()
        server.starttls()
        server.ehlo()
    return server


def main():
    if not ADVISORIES:
        sys.exit("\n[ERROR] No advisories are embedded in this script.\n")

    host, port, sender_name, sender, password, recipients = resolve_credentials()

    print()
    print("  Sending " + str(len(ADVISORIES)) + " advisory(ies) via " + host + ":" + str(port))
    print("  To: " + ", ".join(recipients))
    print("-" * 64)

    try:
        server = connect(host, port)
    except Exception as exc:
        sys.exit("\n[FATAL] Could not connect to " + host + ":" + str(port) +
                 " -- " + str(exc) + "\n")

    if password:
        try:
            server.login(sender, password)
        except smtplib.SMTPAuthenticationError:
            try:
                server.quit()
            except Exception:
                pass
            sys.exit(
                "\n[FATAL] SMTP authentication failed.\n"
                "For Gmail use a 16-character App Password (not your normal password),\n"
                "with 2-Step Verification enabled.\n"
            )
    else:
        print("  (no password entered -- sending without SMTP auth; works only on a relay that allows it)")

    sent = 0
    errors = 0
    for advisory in ADVISORIES:
        subject = advisory.get("subject") or "Security Advisory"
        try:
            message = build_message(advisory, sender_name, sender, recipients)
            server.sendmail(sender, recipients, message.as_string())
            print("  [SENT]   " + _ascii(subject)[:60])
            sent += 1
        except Exception as exc:
            print("  [ERROR]  " + _ascii(subject)[:60])
            print("           " + _ascii(exc))
            errors += 1

    try:
        server.quit()
    except Exception:
        pass

    print("-" * 64)
    print("  Sent   : " + str(sent))
    print("  Errors : " + str(errors))
    print("-" * 64)


if __name__ == "__main__":
    main()
`;

  /**
   * Build the standalone Python sender for a set of advisories.
   * @param {Array} advisories - [{ subject, html, attachments[] }]
   * @param {object} defaults  - suggested prompt values (no password)
   * @returns {string} Python source
   */
  function render(advisories, defaults) {
    const d = defaults || {};
    const payload = {
      defaults: {
        senderName: String(d.senderName || ''),
        senderEmail: String(d.senderEmail || ''),
        host: String(d.host || 'smtp.gmail.com'),
        port: Number(d.port) || 587,
        username: String(d.username || ''),
        recipients: String(d.recipients || '')
      },
      advisories: (Array.isArray(advisories) ? advisories : []).filter(Boolean).map((a) => ({
        subject: String(a.subject || 'Security Advisory'),
        html: String(a.html || ''),
        attachments: (Array.isArray(a.attachments) ? a.attachments : [])
          .filter((at) => at && at.contentId && at.base64)
          .map((at) => ({
            contentId: String(at.contentId || ''),
            base64: String(at.base64 || ''),
            contentType: String(at.contentType || 'image/png'),
            filename: String(at.filename || '')
          }))
      }))
    };
    const b64 = utf8ToBase64(JSON.stringify(payload));
    return PY_TEMPLATE.replace('__PAYLOAD_B64__', b64);
  }

  return { render, utf8ToBase64 };
})();
